import type { ThemeMode } from "@/types";
import type { ThemeTokens } from "@/types/content-config";

export const themeTokens: Record<ThemeMode, ThemeTokens> = {
  light: {
    mode: "light",
    pageBackgroundClass:
      "bg-[linear-gradient(to_right,_#dfe6f2_0%,_#e6e8ec_52%,_#eee7de_92%,_#f4ecdf_100%)] md:bg-[linear-gradient(to_right,_#dfe6f2_0%,_#e6e8ec_72%,_#eee7de_92%,_#f4ecdf_100%)]",
    navTextClass: "text-[#8f9fb4]",
    navActiveClass: "text-[#1266d4]",
    titleClass: "text-[#3d5a7d]",
    bodyClass: "text-[#425d7c]",
    bodyStrongClass: "text-[#32aafc]",
    cardBgClass: "bg-white/25",
    cardBorderClass: "border-white/40",
    cardTextClass: "text-[#095bac]",
    displayBoxBgClass:"bg-[#0a5bac]",
    displayBoxBorderClass:"border-[#f6fbff]",
    softTextClass: "text-[#88a0c0]",
    accentTextClass: "text-[#1266d4]",
    accentSecondaryClass: "text-[#f0aa4f]",
    showcaseOutlineClass: "border-[#4386db]",
    showcaseControlBgClass: "bg-white/60",
    panelBgClass: "bg-[#a5cdf6]/20",
    panelCardBgClass:"bg-white/80",
    dividerClass: "bg-[#bfd0e9]",
    logoClass: "text-[#73a0d1]",
    footerTextClass: "text-[#213a5f]",
    toggleShellClass: "bg-[#8fb3df]",
    dotActiveClass: "bg-[#4b7fbe]",
    dotInactiveClass: "bg-[#9db0cb]",
    emphasis: "bg-[#4da0ff]",
    rightPanelTitle: "text-[#405b76]",
    galleryBgClass:"bg-[#f0f2f7]/60 border-2 border-[#ffffff]/40",

    modalTitle: "text-[#3d5a7d]",
    modalSubheader: "text-[#32aafc]",
    modalOverlayClass: "bg-black/50",
    modalSurfaceClass: "border-white/75 bg-[#f3f4f6]/98",
    modalLeftRailClass: "bg-white/16",
    modalLeftRailBorderClass: "border-white/40",
    modalCloseButtonClass: "border-white/75 bg-white text-[#1e63c8]",
    modalBodyTextClass: "text-[#1e63c8]",
    modalMetaLabelClass: "text-[#6f89ab]",
    modalMetaTextClass: "text-[#3d5a7d]",
    modalTagClass: "border border-white/60 bg-white/45 text-[#1e63c8]",
    modalPrimaryButtonClass: "bg-[#1e63c8] text-white",
    modalSecondaryButtonClass: "border border-[#d6e1f2] bg-white text-[#1e63c8]",
  },

  dark: {
    mode: "dark",
    pageBackgroundClass:
      "bg-[linear-gradient(to_right,_#020912_0%,_#0f2340_42%,_#214575_82%,_#35619b_100%)]",
    navTextClass: "text-[#b4c3d8]",
    navActiveClass: "text-[#4da0ff]",
    titleClass: "text-[#4f96f0]",
    bodyClass: "text-[#f3f6fb]",
    bodyStrongClass: "text-[#ffffff]",
    cardBgClass: "bg-[#8f99ac]/75",
    cardBorderClass: "border-white/90",
    cardTextClass: "text-white",
    displayBoxBgClass:"bg-[#011729]",
    displayBoxBorderClass:"border-[#405b76]",
    softTextClass: "text-[#d7e1f0]",
    accentTextClass: "text-[#4da0ff]",
    accentSecondaryClass: "text-[#ffc44d]",
    showcaseOutlineClass: "border-[#2f86ea]",
    showcaseControlBgClass: "bg-white/90",
    panelBgClass: "bg-[#06274b]/48",
    panelCardBgClass:"bg-[#8f99ac]",
    dividerClass: "bg-[#1f578f]",
    logoClass: "text-white",
    footerTextClass: "text-white",
    toggleShellClass: "bg-[#0b1f3a]",
    dotActiveClass: "bg-[#4da0ff]",
    dotInactiveClass: "bg-[#7b95b7]",
    emphasis: "bg-[#4da0ff]",
    rightPanelTitle: "text-[#d7e1f0]",
    galleryBgClass:"bg-[#000000]/20",

    modalTitle: "text-[#9ce5fd]",
    modalSubheader: "text-white",
    modalOverlayClass: "bg-black/50",
    modalSurfaceClass: "border-white/55 bg-[#7f8da4]/98",
    modalLeftRailClass: "bg-[#5f7391]/45",
    modalLeftRailBorderClass: "border-white/12",
    modalCloseButtonClass: "border-white/55 bg-[#496285] text-white",
    modalBodyTextClass: "text-white",
    modalMetaLabelClass: "text-white/70",
    modalMetaTextClass: "text-white",
    modalTagClass: "border border-white/28 bg-[#4f6586]/70 text-white",
    modalPrimaryButtonClass: "bg-white text-[#17355f]",
    modalSecondaryButtonClass: "border border-white/40 bg-[#496285] text-white",
  },
};